[package]
name = "bilibili-client"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.reqwest]
version = "0.11.11"
features = ["json", "multipart", "cookies"]

[dependencies.tokio]
version = "^1.19"
features = ["full"]

[dependencies.serde_json]
version = "1.0.85"

[dependencies.serde]
version = "1.0.144"
features = ["derive"]

[dependencies.regex]
version = "1.5.4"

[dependencies.qrcode]
version = "0.12"
default-features = false
# optional = true

[dependencies]
rand = "0.8.5"
cookie_store = "0.16.1"
reqwest_cookie_store = "0.3.0"
[[example]]
name = "send_danmaku"
path = "/examples/send-danmaku"